baseURL = 'https://talkor.github.io'
languageCode = 'en-us'
title = 'Tal Koren'
theme = "paper"

[params]
  twitter = 'talkor_'
  github = 'talkor'
  rss = true
  name = 'Tal Koren'
  # bio = 'YOUR_BIO'
  monoDarkIcon = true