baseURL = 'https://talkor.github.io'
languageCode = 'en-us'
title = 'Talko'
theme = "paper"
googleAnalytics = 'G-9086DRHG4Q'

[params]
  twitter = 'talkor_'
  github = 'talkor'
  rss = true
  name = 'Talko'
  # bio = 'YOUR_BIO'
  monoDarkIcon = true
